name: wfc
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2022.10.11=h06a4308_0
  - certifi=2022.9.24=py38h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.3=h5eee18b_3
  - openssl=1.1.1s=h7f8727e_0
  - pip=22.3.1=py38h06a4308_0
  - python=3.8.15=h7a1cb2a_2
  - readline=8.2=h5eee18b_0
  - setuptools=65.5.0=py38h06a4308_0
  - sqlite=3.40.0=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.8=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - about-time==4.2.1
    - alive-progress==3.0.1
    - attrs==22.2.0
    - chardet==5.1.0
    - colorlog==6.7.0
    - contourpy==1.0.6
    - distlib==0.3.6
    - exceptiongroup==1.1.0
    - future==0.18.2
    - grapheme==0.6.0
    - hilbertcurve==2.0.5
    - idna==3.4
    - imageio==2.22.4
    - iniconfig==1.1.1
    - lxml==4.9.2
    - mapbox-earcut==1.0.1
    - matplotlib==3.6.2
    - mpmath==1.2.1
    - networkx==2.8.8
    - opencv-python==4.7.0.68
    - ortools==9.5.2237
    - git+https://github.com/pvigier/perlin-numpy
    - pillow==9.3.0
    - protobuf==4.21.12
    - pycollada==0.7.2
    - pyglet==1.5.0
    - pyparsing==3.0.9
    - pytest==7.2.0
    - ray==2.2.0
    - requests==2.28.1
    - rtree==1.0.1
    - six==1.16.0
    - svg-path==6.2
    - sympy==1.11.1
    - trimesh==3.17.1
    - urllib3==1.26.13
    - virtualenv==20.17.1
    - xxhash==3.2.0
